{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-stack.fullname" . }}-headless
  labels:
    {{- include "kafka-stack.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
    - name: controller
      port: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-stack.fullname" . }}-kafka
  labels:
    {{- include "kafka-stack.labels" . | nindent 4 }}
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka-stack.fullname" . }}-kafka
  labels:
    {{- include "kafka-stack.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kafka-stack.fullname" . }}-headless
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          command: ["/bin/bash", "/opt/kafka/scripts/setup.sh"]
          ports:
            - containerPort: 9092
              name: plaintext
            - containerPort: 9093
              name: controller
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@{{ include "kafka-stack.fullname" . }}-kafka-0.{{ include "kafka-stack.fullname" . }}-headless:9093,2@{{ include "kafka-stack.fullname" . }}-kafka-1.{{ include "kafka-stack.fullname" . }}-headless:9093,3@{{ include "kafka-stack.fullname" . }}-kafka-2.{{ include "kafka-stack.fullname" . }}-headless:9093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).{{ include "kafka-stack.fullname" . }}-headless:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "{{ .Values.kafka.config.autoCreateTopics }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "{{ .Values.kafka.config.offsetsTopicReplicationFactor }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "{{ .Values.kafka.config.transactionStateLogReplicationFactor }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "{{ .Values.kafka.config.transactionStateLogMinIsr }}"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "{{ .Values.kafka.config.defaultReplicationFactor }}"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "{{ .Values.kafka.config.minInsyncReplicas }}"
          resources:
            requests:
              memory: {{ .Values.kafka.resources.requests.memory }}
              cpu: {{ .Values.kafka.resources.requests.cpu }}
            limits:
              memory: {{ .Values.kafka.resources.limits.memory }}
              cpu: {{ .Values.kafka.resources.limits.cpu }}
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
            - name: scripts
              mountPath: /opt/kafka/scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ include "kafka-stack.fullname" . }}-kafka-scripts
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.kafka.storage.storageClass }}
        storageClassName: {{ .Values.kafka.storage.storageClass }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.kafka.storage.size }}
{{- end }}