# Stage 1: Build
FROM maven:3.9.12-eclipse-temurin-25-alpine AS build
WORKDIR /app

COPY kutil/target/kutil-*.jar ./libs/kutil.jar
RUN mvn install:install-file \
   -Dfile=libs/kutil.jar \
   -DgroupId=com.alpine \
   -DartifactId=kutil \
   -Dversion=1.0.0 \
   -Dpackaging=jar

COPY kproducer/pom.xml .
RUN mvn dependency:go-offline

COPY kproducer/src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:25-jre-alpine-3.23
WORKDIR /app

COPY --from=build /app/target/kproducer-*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]