apiVersion: v2
name: kafka-stack
description: A Helm chart for Kafka with producers and consumers
type: application
version: 1.0.0
appVersion: "4.1.1"

dependencies:
  - name: kafka-ui
    version: 1.6.0
    repository: https://kafbat.github.io/helm-charts
#  - name: kubernetes-dashboard
#    version: 7.10.0
#    repository: https://kubernetes.github.io/dashboard